### ISSUE TITLE
Can not run the ./run_mc_anisotropic.sh

### ISSUE THREAD

**Issue by tmquan** [ilastik/nature_methods_multicut_pipeline#1]
Dear ilastik, 

I fell into these errors and could you expose some ways to fix them?
I attempted to build on Ubuntu 16.04 with these commands:
`conda create --name multicut-software --channel ilastik multicut_pipeline`
```
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/tmquan/anaconda2/envs/multicut-software:

The following NEW packages will be INSTALLED:

    boost:             1.55.0-5                                    ilastik
    cplex-shared:      0.1-9                                       ilastik
    decorator:         4.0.11-py27_0                                      
    fftw:              3.3.4-1                                     ilastik
    futures:           3.0.5-py27_0                                       
    graph:             1.6-np19py27_2_g764505d                     ilastik
    h5py:              2.5.0-np19py27_2                                   
    hdf5:              1.8.14-0                                           
    jbig:              2.1-0                                       ilastik
    jpeg:              8d-2                                               
    libgcc:            4.8.5-1999                                  ilastik
    libgfortran:       3.0.0-1                                            
    libpng:            1.6.17-0                                           
    libtiff:           4.0.6-1                                     ilastik
    mkl:               11.3.3-0                                           
    multicut_pipeline: 1.0-py27_6_g985091c                         ilastik
    networkx:          1.11-py27_0                                        
    nose:              1.3.7-py27_1                                       
    numpy:             1.9.3-py27_3                                       
    opengm-thorsten:   2.3.6.post1-np19py27_12_g059e159_with_cplex ilastik
    openssl:           1.0.2k-0                                           
    pip:               9.0.1-py27_1                                       
    python:            2.7.13-0                                           
    readline:          6.2-2                                              
    scikit-learn:      0.16.1-np19py27_0                                  
    scipy:             0.17.1-np19py27_1                                  
    setuptools:        27.2.0-py27_0                                      
    six:               1.10.0-py27_0                                      
    sqlite:            3.13.0-0                                           
    tk:                8.5.18-0                                           
    vigra-thorsten:    1.11-np19py27_3_g575e7eb                    ilastik
    wheel:             0.29.0-py27_0                                      
    wsdt-mcp:          0.1-py27_1_g764505d                         ilastik
    xz:                5.2.2-1                                            
    zlib:              1.2.8-3                                            

Proceed ([y]/n)? y

cplex-shared-0 100% |#############################################################################################################################################| Time: 0:00:00   3.41 MB/s
fftw-3.3.4-1.t 100% |#############################################################################################################################################| Time: 0:00:09 368.24 kB/s
jbig-2.1-0.tar 100% |#############################################################################################################################################| Time: 0:00:00  20.43 MB/s
jpeg-8d-2.tar. 100% |#############################################################################################################################################| Time: 0:00:00 936.66 kB/s
libgcc-4.8.5-1 100% |#############################################################################################################################################| Time: 0:00:02 343.39 kB/s
libgfortran-3. 100% |#############################################################################################################################################| Time: 0:00:00  10.03 MB/s
libpng-1.6.17- 100% |#############################################################################################################################################| Time: 0:00:00   9.92 MB/s
mkl-11.3.3-0.t 100% |#############################################################################################################################################| Time: 0:01:16   1.68 MB/s
openssl-1.0.2k 100% |#############################################################################################################################################| Time: 0:00:01   1.67 MB/s
readline-6.2-2 100% |#############################################################################################################################################| Time: 0:00:00   1.36 MB/s
sqlite-3.13.0- 100% |#############################################################################################################################################| Time: 0:00:04 993.91 kB/s
tk-8.5.18-0.ta 100% |#############################################################################################################################################| Time: 0:00:02 834.60 kB/s
xz-5.2.2-1.tar 100% |#############################################################################################################################################| Time: 0:00:00 970.28 kB/s
zlib-1.2.8-3.t 100% |#############################################################################################################################################| Time: 0:00:00   1.34 MB/s
boost-1.55.0-5 100% |#############################################################################################################################################| Time: 0:00:31 278.93 kB/s
hdf5-1.8.14-0. 100% |#############################################################################################################################################| Time: 0:00:01 962.13 kB/s
libtiff-4.0.6- 100% |#############################################################################################################################################| Time: 0:00:03 403.88 kB/s
python-2.7.13- 100% |#############################################################################################################################################| Time: 0:00:16 717.43 kB/s
decorator-4.0. 100% |#############################################################################################################################################| Time: 0:00:00 599.95 kB/s
futures-3.0.5- 100% |#############################################################################################################################################| Time: 0:00:00 589.35 kB/s
nose-1.3.7-py2 100% |#############################################################################################################################################| Time: 0:00:00 407.93 kB/s
numpy-1.9.3-py 100% |#############################################################################################################################################| Time: 0:00:08 726.09 kB/s
setuptools-27. 100% |#############################################################################################################################################| Time: 0:00:00 565.21 kB/s
six-1.10.0-py2 100% |#############################################################################################################################################| Time: 0:00:00 866.60 kB/s
wheel-0.29.0-p 100% |#############################################################################################################################################| Time: 0:00:00 735.53 kB/s
h5py-2.5.0-np1 100% |#############################################################################################################################################| Time: 0:00:03 682.45 kB/s
networkx-1.11- 100% |#############################################################################################################################################| Time: 0:00:01 708.77 kB/s
pip-9.0.1-py27 100% |#############################################################################################################################################| Time: 0:00:01 831.73 kB/s
scipy-0.17.1-n 100% |#############################################################################################################################################| Time: 0:01:09 453.85 kB/s
vigra-thorsten 100% |#############################################################################################################################################| Time: 0:00:07   1.02 MB/s
graph-1.6-np19 100% |#############################################################################################################################################| Time: 0:00:05 468.55 kB/s
opengm-thorste 100% |#############################################################################################################################################| Time: 0:00:13 734.08 kB/s
scikit-learn-0 100% |#############################################################################################################################################| Time: 0:00:17 471.27 kB/s
wsdt-mcp-0.1-p 100% |#############################################################################################################################################| Time: 0:00:00  21.09 kB/s
multicut_pipel 100% |#############################################################################################################################################| Time: 0:00:00  95.48 kB/s
+ unset CONDA_NPY
+ unset CONDA_PY
++ uname
+ '[' Linux == Darwin ']'
++ ls /opt/ibm/ILOG/CPLEX_Studio127/cplex/lib/x86-64_linux/static_pic/libilocplex.so
+ EXISTING_SHARED_OBJECT=/opt/ibm/ILOG/CPLEX_Studio127/cplex/lib/x86-64_linux/static_pic/libilocplex.so
+ '[' /opt/ibm/ILOG/CPLEX_Studio127/cplex/lib/x86-64_linux/static_pic/libilocplex.so == NOT_PRESENT ']'
+ mkdir -p /home/tmquan/anaconda2/envs/multicut-software/lib
++ uname
+ '[' Linux == Darwin ']'
+ cd /home/tmquan/anaconda2/envs/multicut-software/lib
+ ln -f -s /opt/ibm/ILOG/CPLEX_Studio127/cplex/lib/x86-64_linux/static_pic/libcplex.so
+ ln -f -s /opt/ibm/ILOG/CPLEX_Studio127/concert/lib/x86-64_linux/static_pic/libconcert.so
+ ln -f -s /opt/ibm/ILOG/CPLEX_Studio127/cplex/lib/x86-64_linux/static_pic/libilocplex.so
Found system libstdc++ version: 3.4.21
Found conda  libstdc++ version: 3.4.19
This system has a newer version of libstdc++.so than the one in the libgcc package.
Replacing outdated libstdc++ files...
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libgcc_s.so
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libgcc_s.so.1
Adding link to /lib/x86_64-linux-gnu/libgcc_s.so.1
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libgomp.so
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libgomp.so.1
Adding link to /usr/lib/x86_64-linux-gnu/libgomp.so.1
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libgomp.so.1.0.0
Adding link to /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libquadmath.so
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libquadmath.so.0
Adding link to /usr/lib/x86_64-linux-gnu/libquadmath.so.0
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libquadmath.so.0.0.0
Adding link to /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libstdc++.so
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libstdc++.so.6
Adding link to /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libstdc++.so.6.0.19
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libgfortran.so
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libgfortran.so.3
Adding link to /usr/lib/x86_64-linux-gnu/libgfortran.so.3
Removing /home/tmquan/anaconda2/envs/multicut-software/lib/libgfortran.so.3.0.0
Adding link to /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
#
# To activate this environment, use:
# > source activate multicut-software
#
# To deactivate this environment, use:
# > source deactivate multicut-software
#

```

Then ran the anisotropic propagation
`cd anaconda2/envs/multicut-software/`
`(multicut-software) tmquan@ruby:~/anaconda2/envs/multicut-software$ ./run_mc_anisotropic.sh --use_lifted True --snemi_mode True /home/Pearl/tmquan/test/NaturePaperDataUpl/SNEMI3D/ /home/Pearl/quantm/tmquan/test_SNEMI3D/`

```
Warning: Ignoring your non-empty LD_LIBRARY_PATH
Warning: Ignoring your non-empty PYTHONPATH/PYTHONHOME
Starting Lifted Multicut Workflow
Calculating filter in 3d, with anisotropy factor: 5.0
Calculating filter in 3d, with anisotropy factor: 5.0
Calculating filter in 3d, with anisotropy factor: 5.0
Calculating filter in 3d, with anisotropy factor: 5.0
Running lifted multicut on ds_test
Weights learned on ds_train
Start learning
Computing:  compute_and_save_lifted_nh with args:
(0, 3)
Results will be written in  /home/Pearl/tmquan/test/test_SNEMI3D/cache/ds_test/compute_and_save_lifted_nh_0_3.h5 data
Computing RAG for seg_id 0
Traceback (most recent call last):
  File "/home/tmquan/anaconda2/envs/multicut-software/scripts/run_mc_anisotropic.py", line 256, in <module>
    main()
  File "/home/tmquan/anaconda2/envs/multicut-software/scripts/run_mc_anisotropic.py", line 237, in main
    gamma = gamma, weight_z_lifted = True)
  File "/home/tmquan/anaconda2/envs/multicut-software/multicut_src/MCSolver.py", line 133, in lifted_multicut_workflow
    mc_params)
  File "/home/tmquan/anaconda2/envs/multicut-software/multicut_src/lifted_mc.py", line 578, in learn_and_predict_lifted
    uvIdsTest = compute_and_save_lifted_nh(dsTest, segIdTest, pipelineParam.lifted_neighborhood)
  File "/home/tmquan/anaconda2/envs/multicut-software/multicut_src/Tools.py", line 143, in wrapper
    _res = function(*args)
  File "/home/tmquan/anaconda2/envs/multicut-software/multicut_src/lifted_mc.py", line 464, in compute_and_save_lifted_nh
    rag = ds._rag(segId)
  File "/home/tmquan/anaconda2/envs/multicut-software/multicut_src/DataSet.py", line 252, in _rag
    _rag  = graphs.regionAdjacencyGraph(grid, self.seg(seg_id))
  File "/home/tmquan/anaconda2/envs/multicut-software/lib/python2.7/site-packages/vigra/__init__.py", line 1901, in regionAdjacencyGraph
    reserveEdges=reserveEdges, maxLabel=maxLabel, isDense=isDense)
  File "/home/tmquan/anaconda2/envs/multicut-software/lib/python2.7/site-packages/vigra/__init__.py", line 1428, in __init__
    super(GridRegionAdjacencyGraph, self).__init__(graph, labels, ignoreLabel, reserveEdges, maxLabel, isDense)
  File "/home/tmquan/anaconda2/envs/multicut-software/lib/python2.7/site-packages/vigra/__init__.py", line 1192, in __init__
    self.affiliatedEdges = graphs._regionAdjacencyGraph(graph,labels,self,self.ignoreLabel)
**Boost.Python.ArgumentError: Python argument types in
    vigra.graphs._regionAdjacencyGraph(GridGraphUndirected3d, numpy.ndarray, GridRegionAdjacencyGraph, int)
did not match C++ signature:**
    _regionAdjacencyGraph(vigra::GridGraph<3u, boost::undirected_tag>, vigra::NumpyArray<3u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag>, vigra::AdjacencyListGraph {lvalue}, int)
    _regionAdjacencyGraph(vigra::GridGraph<2u, boost::undirected_tag>, vigra::NumpyArray<2u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag>, vigra::AdjacencyListGraph {lvalue}, int)
    _regionAdjacencyGraph(vigra::AdjacencyListGraph, vigra::NumpyArray<1u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag>, vigra::AdjacencyListGraph {lvalue}, int)
(multicut-software) tmquan@ruby:~/anaconda2/envs/multicut-software$ 
```

Do you happen to know why the current Boost version is not compatible with vigra?

Bests,

**Comment by constantinpape** [comment]
Hi,
as far as I can see, this is not a compatability issue between vigra and boost.
Instead, a vigra function is called with invalid arguments while computing the rag.
I will have a closer look later, but in the meantime, can you try to rerun the command without the --use_lifted and --snemi_mode flags?

**Comment by constantinpape** [comment]
Hi,
I was able to reproduce your error:
the dtype of the over-segmentation that we load in ``snemi_mode`` was not correct (needs to be uint32).

I have fixed this and pushed a commit.
You can either apply the relevant change in the commit (https://github.com/ilastik/nature_methods_multicut_pipeline/commit/a78f34d7e8096289133bd3bad02abd6f03927e6e#diff-b2c6b62f77d3dff13285f56174ba8259) manually in your conda env or rebuild the binaries from the latest commit (see https://github.com/ilastik/nature_methods_multicut_pipeline#installation).

Let me know if this solve your issue. Also, I would advise you to first run the pipeline without the lifted multicut option, as this should be much faster and less RAM consuming and only use the lifted multicut once this has succeeded.

**Comment by constantinpape** [comment]
While running the example, I ran into another problem caused by the fact that the segmentation is not consecutive.
I have also fixed it with a new commit: https://github.com/ilastik/nature_methods_multicut_pipeline/commit/703fd2bb92072e38d25388b636aabd87733916d6

**Comment by tmquan** [comment]
@constantinpape : Thanks for your help. 

I attempted to run without any option on your new commit, still it threw the same error:

./run_mc_anisotropic.sh  ~/NaturePaperDataUpl/SNEMI3D/ ~/test_SNEMI3D
Warning: Ignoring your non-empty LD_LIBRARY_PATH
Warning: Ignoring your non-empty PYTHONPATH/PYTHONHOME
Generating initial cache, this may take some minutes
Traceback (most recent call last):
  File "/usr/envs/multicut-software/scripts/run_mc_anisotropic.py", line 270, in <module>
    main()
  File "/usr/envs/multicut-software/scripts/run_mc_anisotropic.py", line 198, in main
    init(args.data_folder, cache_folder, args.snemi_mode )
  File "/usr/envs/multicut-software/scripts/run_mc_anisotropic.py", line 148, in init
    seg_train = wsdt( probs_train )
  File "/usr/envs/multicut-software/scripts/run_mc_anisotropic.py", line 79, in wsdt
    **wsdt, _, _ = vigra.analysis.relabelConsecutive(wsdt, start_label = 0, keep_zeros = False)**
Boost.Python.ArgumentError: Python argument types in
    vigra.analysis.relabelConsecutive(numpy.ndarray)
did not match C++ signature:
    relabelConsecutive(vigra::NumpyArray<1u, vigra::Singleband<unsigned long>, vigra::StridedArrayTag> labels, unsigned int start_label=0, vigra::NumpyArray<1u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<1u, vigra::Singleband<unsigned char>, vigra::StridedArrayTag> labels, unsigned char start_label=0, vigra::NumpyArray<1u, vigra::Singleband<unsigned char>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<1u, vigra::Singleband<unsigned long>, vigra::StridedArrayTag> labels, unsigned long start_label=0, vigra::NumpyArray<1u, vigra::Singleband<unsigned long>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<1u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> labels, unsigned int start_label=0, vigra::NumpyArray<1u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<2u, vigra::Singleband<unsigned long>, vigra::StridedArrayTag> labels, unsigned int start_label=0, vigra::NumpyArray<2u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<2u, vigra::Singleband<unsigned char>, vigra::StridedArrayTag> labels, unsigned char start_label=0, vigra::NumpyArray<2u, vigra::Singleband<unsigned char>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<2u, vigra::Singleband<unsigned long>, vigra::StridedArrayTag> labels, unsigned long start_label=0, vigra::NumpyArray<2u, vigra::Singleband<unsigned long>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<2u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> labels, unsigned int start_label=0, vigra::NumpyArray<2u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<3u, vigra::Singleband<unsigned long>, vigra::StridedArrayTag> labels, unsigned int start_label=0, vigra::NumpyArray<3u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<3u, vigra::Singleband<unsigned char>, vigra::StridedArrayTag> labels, unsigned char start_label=0, vigra::NumpyArray<3u, vigra::Singleband<unsigned char>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<3u, vigra::Singleband<unsigned long>, vigra::StridedArrayTag> labels, unsigned long start_label=0, vigra::NumpyArray<3u, vigra::Singleband<unsigned long>, vigra::StridedArrayTag> out=None)
    relabelConsecutive(vigra::NumpyArray<3u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> labels, unsigned int start_label=0, vigra::NumpyArray<3u, vigra::Singleband<unsigned int>, vigra::StridedArrayTag> out=None)

**Comment by constantinpape** [comment]
No, this is a different error.
A similar error message always pops up, when a vigra function is called from python with non-matching arguments.
In this case, the error is caused by some of the changes I have made. Apparently you are using an older vigra version than me.
Anyway, I have pushed a new commit that should run with all vigra versions. Please try to rerun with it.

**Comment by tmquan** [comment]
Thanks for the commit. 

However, your fixes gave me these errors. 
Do you have any idea to overcome this issue? And could you update the conda library so that the necessary packages are up-to-date?

> ./run_mc_anisotropic.sh ~/NaturePaperDataUpl/SNEMI3D/ ~/test_SNEMI3D
```
Warning: Ignoring your non-empty LD_LIBRARY_PATH
Warning: Ignoring your non-empty PYTHONPATH/PYTHONHOME
Starting Multicut Workflow
Running multicut on ds_test
Weights learned on ds_train
with solver opengm_fusionmoves
Learning random forest with 500 trees
Starting Inference
Traceback (most recent call last):
  File "/usr/envs/multicut-software/scripts/run_mc_anisotropic.py", line 256, in <module>
    main()
  File "/usr/envs/multicut-software/scripts/run_mc_anisotropic.py", line 246, in main
    local_feats_list, exp_params)
  File "/usr/envs/multicut-software/multicut_src/MCSolver.py", line 80, in multicut_workflow
    edge_energies, mc_params)
  File "/usr/envs/multicut-software/multicut_src/MCSolverImpl.py", line 209, in multicut_fusionmoves
    inf.infer()
  File "/usr/envs/multicut-software/lib/python2.7/site-packages/opengm/_inference_interface_generator.py", line 590, in _f_
    return attr(*args,**kwargs)
  File "/usr/envs/multicut-software/lib/python2.7/site-packages/opengm/_inference_injector.py", line 176, in infer
    return self._infer_no_visitor(releaseGil=releaseGil)
RuntimeError: unidentifiable C++ exception

```

**Comment by constantinpape** [comment]
This is an error in the multicut solver.
Did you link against CPLEX, as described in the README here:
https://github.com/ilastik/nature_methods_multicut_pipeline/tree/master/software/scripts

**Comment by DerThorsten** [comment]
Looks to me like some cplex-ish error.
Which cplex version are you using?

**Comment by constantinpape** [comment]
@DerThorsten: I think the problem is that cplex is not linked at all.
We forgot to mention this step in the top-level readme (I am updating it right now).

**Comment by tmquan** [comment]
@DerThorsten : 

I used the CPLEX_Studio_Community1263.

**Comment by DerThorsten** [comment]
Community Edition:
"Problem size limited to 1000 variables and 1000 constraints. All features included. Available on the most popular supported platforms."
https://www-01.ibm.com/software/websphere/products/optimization/cplex-studio-community-edition/

I am very certain that this is the problem.
@tmquan, you could try the 'Extended trial' version or try to get a CPLE licence via ' Academic Initiative'

1000 variable and 1000 contraints seems to low to run snemi ( @constantinpape , do you know the number of vars for snemi ?)

**Comment by constantinpape** [comment]
@tmquan 

And did you run the 
$ ./install-cplex-shared-libs.sh /path/to/cplex-dir /path/to/multicut-binaries
command ?

**Comment by constantinpape** [comment]
@tmquan 
Ok, as Thorsten has pointed out the problem seems to be caused by the fact that you are using the community edition. It can only handle problems much smaller than the ones we need to solve.
Please get the academic version (for instructions see http://ilastik.org/documentation/basics/installation.html#tocAnchor-1-1-1) and retry.

@DerThorsten:
Is CPLEX needed for the solver we are using for the lifted multicut?
If not, it should run with the use lifted option.

**Comment by DerThorsten** [comment]
@constantinpape 
CPLEX is not needed for the lifted mc itself, but as far as I remeber, we use the multicut results as features within the lifted feature computation

**Comment by constantinpape** [comment]
@DerThorsten 
Nope, we are not using these features in the experiment scripts, because they turned out not to be critical for the accuracy of the LMC.
Regarding the number of variables: It's more than 10^5 for SNEMI.

@tmquan:
Please try to rerun the pipeline with both ``use_lifted = True`` and ``snemi_mode = True``, this should not depend on your CPLEX version. Note that this option may take some time (~ 1 day) and is quite RAM hungry (you should at least have 128 GB of RAM for this, I am currently working on a fix for this issue).
Anyway, I would still advise to get the academic CPLEX version,  because debugging the pipeline is easier when running the normal multicut mode.

**Comment by tmquan** [comment]
@DerThorsten @constantinpape 👍 Thanks for the instruction

I installed CPLEX 127 academic version. When I ran with both use_lifted = True and snemi_mode = True, it threw this error:

Warning: TIFFDecoder: no TIFFTAG_SAMPLEFORMAT or TIFFTAG_DATATYPE, guessing pixeltype 'UINT16'.
Starting Lifted Multicut Workflow
Calculating filter in 3d, with anisotropy factor: 5.0
Calculating filter in 3d, with anisotropy factor: 5.0
Calculating filter in 3d, with anisotropy factor: 5.0
Calculating filter in 3d, with anisotropy factor: 5.0
Running lifted multicut on ds_test
Weights learned on ds_train
Start learning
Computing:  compute_and_save_lifted_nh with args:
(0, 3)
Results will be written in  ~/test_SNEMI3D/cache/ds_test/compute_and_save_lifted_nh_0_3.h5 data
Computing RAG for seg_id 0
WRITING IN  ~/test_SNEMI3D/cache/ds_test/rag_seg0.h5 rag
python: /miniconda/conda-bld/graph_1480389181293/work/dependencies/graph-1.6/include/andres/graph/graph.hxx:329: std::size_t andres::graph::Graph<VISITOR>::insertEdge(std::size_t, std::size_t) [with VISITOR = andres::graph::IdleGraphVisitor<long unsigned int>; std::size_t = long unsigned int]: Assertion `vertexIndex0 < numberOfVertices()' failed.
./run_mc_anisotropic.sh: line 5: 18610 Aborted                 (core dumped) ${PREFIX}/bin/python ${PREFIX}/scripts/run_mc_anisotropic.py "$@"

**Comment by constantinpape** [comment]
There seems to be an issue with the over-segmentation.
I was not able to reproduce this, so I am assuming that this is some problem with the cached files please do the following:

* Go to the directory test_SNEMI3D/cache/ds_test. There should be a file called _adjacent_segments.h5.
Please upload it.
* Check out the latest commit (I have fixed some unrelated issues).
* Delete the complete cache folder and start the experiment again.

**Comment by constantinpape** [comment]
Make sure to use the latest commits, I have fixed some more issues with the lifted multicut.
On my machine everything runs through with ``use_lifted = True`` and ``snemi_mode = True`` now.

**Comment by tmquan** [comment]
@constantinpape : the latest commits finally worked. 
Thank you for your helps :)

**Comment by constantinpape** [comment]
Glad we could help, let us know if you want to try it on your own data and run into any problems.
