### ISSUE TITLE
Permission denied when trying to access files

### ISSUE THREAD

**Issue by constantinpape** [ilastik/nature_methods_multicut_pipeline#5]
I tried to access https://files.ilastik.org/multicut/ but get a 403.
Any ideas what might cause this, @k-dominik?

**Comment by k-dominik** [comment]
browsing of our directories is not permitted anymore due to security concerns

direct links will still work though, so is it the `multicut-software-*` stuff you'd want to share?

**Comment by constantinpape** [comment]
> direct links will still work though, so is it the `multicut-software-*` stuff you'd want to share?

I was actually looking for some of the other data that we have uploaded there.
But it would also be good to update the link for the software stuff in the README.
